In [47]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix, cohen_kappa_score, accuracy_score, classification_report
from sklearn.model_selection import train_test_split

In [18]:
file = pd.read_csv(r"C:\Users\MJ\Desktop\ML\CSV's\titanic.csv")
file.head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

In [25]:
file = file.drop('SexCode', axis = 1)
file = file.drop('Name', axis = 1)

KeyError: "['SexCode'] not found in axis"

In [26]:
file = file.replace(['female', 'male', '1st', '2nd', '3rd'], [1, 2, 1, 2, 3])

In [31]:
def classify_report(ytest, y_pred):
    cf = classification_report(ytest, y_pred)
    print("Classification Report: \n")
    print(cf)
    cm = confusion_matrix(ytest, y_pred)
    print("Confusion Matrix: \n", cm)
    error_rate = 1 - accuracy_score(ytest, y_pred)                
    print("Error Rate: \n", error_rate)
    print("Accuracy: \n", accuracy_score(ytest, y_pred))
    print("Kappa Score: \n", cohen_kappa_score(ytest, y_pred))

In [45]:
mean = file['Age'].mean()
file['Age'] = file['Age'].fillna(mean)

In [53]:
from sklearn.naive_bayes import GaussianNB

x = file.iloc[:, :3].values
y = file.iloc[:, 3].values
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.3, random_state = 0)

gnb = GaussianNB()

gnb.fit(xtrain, ytrain)

y_pred_nb = gnb.predict(xtest)

classify_report(ytest, y_pred_nb)

Classification Report: 

              precision    recall  f1-score   support

           0       0.86      0.72      0.79       264
           1       0.58      0.76      0.66       130

    accuracy                           0.74       394
   macro avg       0.72      0.74      0.72       394
weighted avg       0.77      0.74      0.74       394

Confusion Matrix: 
 [[191  73]
 [ 31  99]]
Error Rate: 
 0.2639593908629442
Accuracy: 
 0.7360406091370558
Kappa Score: 
 0.448268433241773


In [54]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors = 5)

knn.fit(xtrain, ytrain)

y_pred_knn = knn.predict(xtest)

classify_report(ytest, y_pred_knn)

Classification Report: 

              precision    recall  f1-score   support

           0       0.84      0.80      0.82       264
           1       0.62      0.68      0.65       130

    accuracy                           0.76       394
   macro avg       0.73      0.74      0.73       394
weighted avg       0.77      0.76      0.76       394

Confusion Matrix: 
 [[210  54]
 [ 41  89]]
Error Rate: 
 0.24111675126903553
Accuracy: 
 0.7588832487309645
Kappa Score: 
 0.46818788894887897


In [56]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier(n_estimators = 5)

rfc.fit(xtrain, ytrain)

y_pred_rfc = rfc.predict(xtest)

classify_report(ytest, y_pred_rfc)

Classification Report: 

              precision    recall  f1-score   support

           0       0.83      0.90      0.86       264
           1       0.75      0.63      0.69       130

    accuracy                           0.81       394
   macro avg       0.79      0.76      0.77       394
weighted avg       0.81      0.81      0.80       394

Confusion Matrix: 
 [[237  27]
 [ 48  82]]
Error Rate: 
 0.19035532994923854
Accuracy: 
 0.8096446700507615
Kappa Score: 
 0.5510892352565855


In [57]:
from sklearn.svm import SVC

svcclassifier = SVC()
svcclassifier.fit(xtrain, ytrain)
y_pred_svm = svcclassifier.predict(xtest)

classify_report(ytest, y_pred_svm)

Classification Report: 

              precision    recall  f1-score   support

           0       0.69      0.99      0.81       264
           1       0.80      0.09      0.17       130

    accuracy                           0.69       394
   macro avg       0.74      0.54      0.49       394
weighted avg       0.73      0.69      0.60       394

Confusion Matrix: 
 [[261   3]
 [118  12]]
Error Rate: 
 0.30710659898477155
Accuracy: 
 0.6928934010152284
Kappa Score: 
 0.1043772308848393
